server:
       port: 8888
       contextPath: /v1
               
       error:
             whitelabel:
                        enabled: false

spring:
       profiles:
                active: dev
       devtools:
                livereload:
                           enabled: true
       http:
            encoding:
                     charset: UTF-8
                     enabled: true
                     forced: true
                     forced-request: true
                     forced-response: true
       aop:
           auto: true
       aop-proxy-target-class: true


       datasource:
                  driver-class-name: org.mariadb.jdbc.Driver
                  url: jdbc:mariadb://localhost:3306/pjmall
                  username: pjmall
                  password: pjmall


security:
         user:
              name: test
              password: 5678
#         oauth2:
#                client:
#                       client-id: pjmall
#                       client-secret: 1234
       